spring:
  application:
    name: blackjack-app
  datasource:
    url: jdbc:postgresql://aws-2020.cjddqt3kzww8.us-west-2.rds.amazonaws.com:5432/blackjack?
    username: blackjack
    password: p4ssw0rd
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        format-sql: true
  